import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="id" className="dark"> 
      <body className="bg-gray-950 text-white antialiased min-h-screen overflow-x-hidden">
        <div className="flex">
          {/* Sidebar */}
          <Sidebar />

          {/* Konten Utama */}
          <main className="flex-1 min-h-screen ml-64 bg-gray-950">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
